name: Lint & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          level: info
      - uses: gwatts/go-coverage-action@v1
        id: coverage
        with:
          cover-pkg: ./...
          report-url: https://artifacts.example.com/go-coverage/${{ github.ref_name}}.html

      - run: go test -coverprofile=coverage.txt -covermode=atomic ./...
      - uses: codecov/codecov-action@v1

      - name: Collect dependencies
        run: go install gotest.tools/gotestsum@latest

      - name: Run unit tests
        run: gotestsum --junitfile unit-tests.xml -- -gcflags=-l ./...

      - name: Test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test report
          path: unit-tests.xml
          reporter: java-junit
          fail-on-error: false
